# Generated by Django 4.2 on 2023-07-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='volunteertbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='messagetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='fundraiseTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('freq', models.IntegerField(choices=[(1, 'Monthly'), (2, 'One-Time')])),
                ('category', models.IntegerField(choices=[(1, 'Charity'), (2, 'Campaign')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='donateTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(choices=[(1, 'Monthly'), (2, 'One-Time')])),
                ('dtype', models.IntegerField(default=False)),
                ('category', models.IntegerField(choices=[(1, 'Charity'), (2, 'Campaign')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='campaignTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.IntegerField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser')),
            ],
        ),
    ]
