# Generated by Django 4.2 on 2023-07-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertbl',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteertbl',
            name='dtype',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='volunteertbl',
            name='freq',
            field=models.IntegerField(choices=[(1, 'Monthly'), (2, 'One-Time')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigntbl',
            name='category',
            field=models.IntegerField(choices=[(1, 'cancer awareness campaign'), (2, 'fundraise campaign'), (3, 'pulse polio campaign'), (4, 'annual health care campaign')]),
        ),
    ]
