# Generated by Django 4.2 on 2023-07-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_messagetbl_username_alter_messagetbl_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetbl',
            name='name',
        ),
        migrations.AddField(
            model_name='messagetbl',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.registereduser'),
            preserve_default=False,
        ),
    ]
