# Generated by Django 4.2 on 2023-07-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_messagetbl_name_messagetbl_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteertbl',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='volunteertbl',
            name='dtype',
        ),
    ]
