# Generated by Django 4.2 on 2023-07-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_volunteertbl_amount_remove_volunteertbl_dtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteertbl',
            name='name',
        ),
    ]
